use url::Url;

/// ════════════════════════════════════════════════════════════════════
/// Sandbox: WHITELIST of allowed URL schemes
/// 
/// Called from:
/// 1. IPC handler (before sending Navigate event)
/// 2. Navigation handler (before allowing any URL load)
/// 3. New window handler (before allowing popup)
/// 
/// SECURITY: This is the primary boundary. Deny by default.
/// ════════════════════════════════════════════════════════════════════

pub fn sandbox_allow_navigation(url: &str) -> bool {
    println!("[sandbox] Checking: {}", url);

    // SECURITY: Parse first, fail closed if invalid
    match Url::parse(url) {
        Ok(parsed) => {
            let scheme = parsed.scheme();
            println!("[sandbox] Scheme: {}", scheme);

            match scheme {
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✓ ALLOWED: Network schemes
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "http" | "https" => {
                    println!("[sandbox] ✓ Network (http/https): {}", url);
                    true
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✓ ALLOWED: WebSocket (validated at network layer)
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "ws" | "wss" => {
                    println!("[sandbox] ✓ WebSocket (ws/wss): {}", url);
                    true
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✓ ALLOWED: About pages (minimal functionality)
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "about" => {
                    println!("[sandbox] ✓ About pages: {}", url);
                    true
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✓ ALLOWED: Blob URLs (generated by web apps)
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "blob" => {
                    println!("[sandbox] ✓ Blob URL: {}", url);
                    true
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ⚠ RESTRICTED: Data URLs (only images allowed)
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "data" => {
                    // Only allow data:image/*
                    if url.starts_with("data:image/") {
                        println!("[sandbox] ⚠ Data image URL: {}", url);
                        true
                    } else {
                        eprintln!("[sandbox] ✗ Non-image data URL blocked: {}", url);
                        false
                    }
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✗ BLOCKED: Code execution
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "javascript" => {
                    eprintln!("[sandbox] ✗ JavaScript URL blocked: {}", url);
                    false
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✗ BLOCKED: Local file access
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "file" => {
                    eprintln!("[sandbox] ✗ File access blocked: {}", url);
                    false
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✗ BLOCKED: FTP (legacy)
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "ftp" | "ftps" => {
                    eprintln!("[sandbox] ✗ FTP access blocked: {}", url);
                    false
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✗ BLOCKED: Source inspection
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "view-source" => {
                    eprintln!("[sandbox] ✗ View-source blocked: {}", url);
                    false
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✗ BLOCKED: External app invocation
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "mailto" | "tel" | "sms" | "geo" => {
                    eprintln!("[sandbox] ✗ External app scheme blocked: {}", url);
                    false
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✓ ALLOWED: Internal schemes (asset, ipc)
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                "asset" | "ipc" => {
                    println!("[sandbox] ✓ Internal scheme: {}", scheme);
                    true
                }

                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // ✗ DEFAULT: Deny unknown schemes (fail closed)
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                other => {
                    eprintln!(
                        "[sandbox] ✗ Unknown scheme '{}' denied by default: {}",
                        other, url
                    );
                    false
                }
            }
        }

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // ✗ Parse error: Deny (fail closed)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        Err(e) => {
            eprintln!("[sandbox] ✗ Invalid URL (parse error): {} — {}", url, e);
            false
        }
    }
}

#[cfg(test)]
mod tests {
    use super::sandbox_allow_navigation;

    // ════════════════════════════════════════════════════════
    // Allowed schemes
    // ════════════════════════════════════════════════════════

    #[test]
    fn allows_https() {
        assert!(sandbox_allow_navigation("https://example.com"));
    }

    #[test]
    fn allows_http() {
        assert!(sandbox_allow_navigation("http://example.com"));
    }

    #[test]
    fn allows_websocket() {
        assert!(sandbox_allow_navigation("ws://example.com/socket"));
        assert!(sandbox_allow_navigation("wss://example.com/socket"));
    }

    #[test]
    fn allows_blob() {
        assert!(sandbox_allow_navigation("blob:https://example.com/12345"));
    }

    #[test]
    fn allows_about() {
        assert!(sandbox_allow_navigation("about:blank"));
    }

    #[test]
    fn allows_image_data_urls() {
        assert!(sandbox_allow_navigation("data:image/png;base64,iVBORw0KGgo="));
        assert!(sandbox_allow_navigation("data:image/svg+xml,<svg></svg>"));
    }

    #[test]
    fn allows_asset_scheme() {
        assert!(sandbox_allow_navigation("asset://index.html"));
        assert!(sandbox_allow_navigation("asset://blocked.html"));
    }

    #[test]
    fn allows_ipc_scheme() {
        assert!(sandbox_allow_navigation("ipc://navigate?q=example"));
    }

    // ════════════════════════════════════════════════════════
    // Blocked schemes
    // ════════════════════════════════════════════════════════

    #[test]
    fn blocks_javascript() {
        assert!(!sandbox_allow_navigation("javascript:alert('xss')"));
    }

    #[test]
    fn blocks_file() {
        assert!(!sandbox_allow_navigation("file:///etc/passwd"));
    }

    #[test]
    fn blocks_view_source() {
        assert!(!sandbox_allow_navigation("view-source:https://example.com"));
    }

    #[test]
    fn blocks_non_image_data_urls() {
        assert!(!sandbox_allow_navigation("data:text/html,<h1>xss</h1>"));
        assert!(!sandbox_allow_navigation("data:text/javascript,alert(1)"));
    }

    #[test]
    fn blocks_external_app_schemes() {
        assert!(!sandbox_allow_navigation("mailto:test@example.com"));
        assert!(!sandbox_allow_navigation("tel:+1234567890"));
        assert!(!sandbox_allow_navigation("sms:+1234567890"));
    }

    #[test]
    fn blocks_ftp() {
        assert!(!sandbox_allow_navigation("ftp://example.com"));
    }

    #[test]
    fn blocks_invalid_urls() {
        assert!(!sandbox_allow_navigation("ht!tp://[invalid"));
        assert!(!sandbox_allow_navigation(""));
    }
}